version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-react-redux-starter-kit-{{ checksum "yarn.lock" }}
            - v1-react-redux-starter-kit-
      - run: npm install
      - run: npm test
      - save_cache:
          key: v1-react-redux-starter-kit-{{ checksum "yarn.lock" }}
          paths:
            - ~/tmp/node_modules
      # Save artifacts
      - store_artifacts:
          path: ~/tmp/artifacts
          destination: build
      # Upload test results
      - store_test_results:
          path: ~/tmp/test-reports
